//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CN100.Redis.Client
{
    
    
    /// <summary>
    /// The RedisSection Configuration Section.
    /// </summary>
    public partial class RedisSection : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the RedisSection Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        internal const string RedisSectionSectionName = "RedisSection";
        
        /// <summary>
        /// Gets the RedisSection instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        public static global::CN100.Redis.Client.RedisSection Instance
        {
            get
            {
                return ((global::CN100.Redis.Client.RedisSection)(global::System.Configuration.ConfigurationManager.GetSection(global::CN100.Redis.Client.RedisSection.RedisSectionSectionName)));
            }
        }
        #endregion
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::CN100.Redis.Client.RedisSection.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::CN100.Redis.Client.RedisSection.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region RedisGroup Property
        /// <summary>
        /// The XML name of the <see cref="RedisGroup"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        internal const string RedisGroupPropertyName = "RedisGroup";
        
        /// <summary>
        /// Gets or sets the RedisGroup.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        [global::System.ComponentModel.DescriptionAttribute("The RedisGroup.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::CN100.Redis.Client.RedisSection.RedisGroupPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=true)]
        public virtual global::CN100.Redis.Client.RedisGroup RedisGroup
        {
            get
            {
                return ((global::CN100.Redis.Client.RedisGroup)(base[global::CN100.Redis.Client.RedisSection.RedisGroupPropertyName]));
            }
            set
            {
                base[global::CN100.Redis.Client.RedisSection.RedisGroupPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace CN100.Redis.Client
{
    
    
    /// <summary>
    /// A collection of Server instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::CN100.Redis.Client.Server), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::CN100.Redis.Client.host.ServerPropertyName)]
    public partial class host : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::CN100.Redis.Client.Server"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        internal const string ServerPropertyName = "add";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        protected override string ElementName
        {
            get
            {
                return global::CN100.Redis.Client.host.ServerPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::CN100.Redis.Client.host.ServerPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::CN100.Redis.Client.Server)(element)).ipAddress;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::CN100.Redis.Client.Server"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::CN100.Redis.Client.Server"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::CN100.Redis.Client.Server();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::CN100.Redis.Client.Server"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::CN100.Redis.Client.Server"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        public global::CN100.Redis.Client.Server this[int index]
        {
            get
            {
                return ((global::CN100.Redis.Client.Server)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::CN100.Redis.Client.Server"/> with the specified key.
        /// </summary>
        /// <param name="ipAddress">The key of the <see cref="global::CN100.Redis.Client.Server"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        public global::CN100.Redis.Client.Server this[object ipAddress]
        {
            get
            {
                return ((global::CN100.Redis.Client.Server)(base.BaseGet(ipAddress)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::CN100.Redis.Client.Server"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="add">The <see cref="global::CN100.Redis.Client.Server"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        public void Add(global::CN100.Redis.Client.Server add)
        {
            base.BaseAdd(add);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::CN100.Redis.Client.Server"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="add">The <see cref="global::CN100.Redis.Client.Server"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        public void Remove(global::CN100.Redis.Client.Server add)
        {
            base.BaseRemove(this.GetElementKey(add));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::CN100.Redis.Client.Server"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::CN100.Redis.Client.Server"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        public global::CN100.Redis.Client.Server GetItemAt(int index)
        {
            return ((global::CN100.Redis.Client.Server)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::CN100.Redis.Client.Server"/> with the specified key.
        /// </summary>
        /// <param name="ipAddress">The key of the <see cref="global::CN100.Redis.Client.Server"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        public global::CN100.Redis.Client.Server GetItemByKey(string ipAddress)
        {
            return ((global::CN100.Redis.Client.Server)(base.BaseGet(((object)(ipAddress)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region db Property
        /// <summary>
        /// The XML name of the <see cref="db"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        internal const string dbPropertyName = "db";
        
        /// <summary>
        /// Gets or sets the db.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        [global::System.ComponentModel.DescriptionAttribute("The db.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::CN100.Redis.Client.host.dbPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual long db
        {
            get
            {
                return ((long)(base[global::CN100.Redis.Client.host.dbPropertyName]));
            }
            set
            {
                base[global::CN100.Redis.Client.host.dbPropertyName] = value;
            }
        }
        #endregion
        
        #region connectName Property
        /// <summary>
        /// The XML name of the <see cref="connectName"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        internal const string connectNamePropertyName = "connectName";
        
        /// <summary>
        /// Gets or sets the connectName.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        [global::System.ComponentModel.DescriptionAttribute("The connectName.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::CN100.Redis.Client.host.connectNamePropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string connectName
        {
            get
            {
                return ((string)(base[global::CN100.Redis.Client.host.connectNamePropertyName]));
            }
            set
            {
                base[global::CN100.Redis.Client.host.connectNamePropertyName] = value;
            }
        }
        #endregion
        
        #region MaxReadPoolSize Property
        /// <summary>
        /// The XML name of the <see cref="MaxReadPoolSize"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        internal const string MaxReadPoolSizePropertyName = "maxReadPoolSize";
        
        /// <summary>
        /// Gets or sets the MaxReadPoolSize.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        [global::System.ComponentModel.DescriptionAttribute("The MaxReadPoolSize.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::CN100.Redis.Client.host.MaxReadPoolSizePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual int MaxReadPoolSize
        {
            get
            {
                return ((int)(base[global::CN100.Redis.Client.host.MaxReadPoolSizePropertyName]));
            }
            set
            {
                base[global::CN100.Redis.Client.host.MaxReadPoolSizePropertyName] = value;
            }
        }
        #endregion
        
        #region MaxWritePoolSize Property
        /// <summary>
        /// The XML name of the <see cref="MaxWritePoolSize"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        internal const string MaxWritePoolSizePropertyName = "maxWritePoolSize";
        
        /// <summary>
        /// Gets or sets the MaxWritePoolSize.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        [global::System.ComponentModel.DescriptionAttribute("The MaxWritePoolSize.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::CN100.Redis.Client.host.MaxWritePoolSizePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual int MaxWritePoolSize
        {
            get
            {
                return ((int)(base[global::CN100.Redis.Client.host.MaxWritePoolSizePropertyName]));
            }
            set
            {
                base[global::CN100.Redis.Client.host.MaxWritePoolSizePropertyName] = value;
            }
        }
        #endregion
    }
}
namespace CN100.Redis.Client
{
    
    
    /// <summary>
    /// The Server Configuration Element.
    /// </summary>
    public partial class Server : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region ipAddress Property
        /// <summary>
        /// The XML name of the <see cref="ipAddress"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        internal const string ipAddressPropertyName = "ipAddress";
        
        /// <summary>
        /// Gets or sets the ipAddress.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        [global::System.ComponentModel.DescriptionAttribute("The ipAddress.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::CN100.Redis.Client.Server.ipAddressPropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string ipAddress
        {
            get
            {
                return ((string)(base[global::CN100.Redis.Client.Server.ipAddressPropertyName]));
            }
            set
            {
                base[global::CN100.Redis.Client.Server.ipAddressPropertyName] = value;
            }
        }
        #endregion
        
        #region port Property
        /// <summary>
        /// The XML name of the <see cref="port"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        internal const string portPropertyName = "port";
        
        /// <summary>
        /// Gets or sets the port.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        [global::System.ComponentModel.DescriptionAttribute("The port.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::CN100.Redis.Client.Server.portPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string port
        {
            get
            {
                return ((string)(base[global::CN100.Redis.Client.Server.portPropertyName]));
            }
            set
            {
                base[global::CN100.Redis.Client.Server.portPropertyName] = value;
            }
        }
        #endregion
        
        #region RedMod Property
        /// <summary>
        /// The XML name of the <see cref="RedMod"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        internal const string RedModPropertyName = "redMod";
        
        /// <summary>
        /// Gets or sets the RedMod.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        [global::System.ComponentModel.DescriptionAttribute("The RedMod.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::CN100.Redis.Client.Server.RedModPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::System.ReadMod RedMod
        {
            get
            {
                return ((global::System.ReadMod)(base[global::CN100.Redis.Client.Server.RedModPropertyName]));
            }
            set
            {
                base[global::CN100.Redis.Client.Server.RedModPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace CN100.Redis.Client
{
    
    
    /// <summary>
    /// A collection of host instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::CN100.Redis.Client.host), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::CN100.Redis.Client.RedisGroup.hostPropertyName)]
    public partial class RedisGroup : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::CN100.Redis.Client.host"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        internal const string hostPropertyName = "host";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        protected override string ElementName
        {
            get
            {
                return global::CN100.Redis.Client.RedisGroup.hostPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::CN100.Redis.Client.RedisGroup.hostPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::CN100.Redis.Client.host)(element)).connectName;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::CN100.Redis.Client.host"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::CN100.Redis.Client.host"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::CN100.Redis.Client.host();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::CN100.Redis.Client.host"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::CN100.Redis.Client.host"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        public global::CN100.Redis.Client.host this[int index]
        {
            get
            {
                return ((global::CN100.Redis.Client.host)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::CN100.Redis.Client.host"/> with the specified key.
        /// </summary>
        /// <param name="connectName">The key of the <see cref="global::CN100.Redis.Client.host"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        public global::CN100.Redis.Client.host this[object connectName]
        {
            get
            {
                return ((global::CN100.Redis.Client.host)(base.BaseGet(connectName)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::CN100.Redis.Client.host"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="host">The <see cref="global::CN100.Redis.Client.host"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        public void Add(global::CN100.Redis.Client.host host)
        {
            base.BaseAdd(host);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::CN100.Redis.Client.host"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="host">The <see cref="global::CN100.Redis.Client.host"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        public void Remove(global::CN100.Redis.Client.host host)
        {
            base.BaseRemove(this.GetElementKey(host));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::CN100.Redis.Client.host"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::CN100.Redis.Client.host"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        public global::CN100.Redis.Client.host GetItemAt(int index)
        {
            return ((global::CN100.Redis.Client.host)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::CN100.Redis.Client.host"/> with the specified key.
        /// </summary>
        /// <param name="connectName">The key of the <see cref="global::CN100.Redis.Client.host"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        public global::CN100.Redis.Client.host GetItemByKey(string connectName)
        {
            return ((global::CN100.Redis.Client.host)(base.BaseGet(((object)(connectName)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace System
{
    
    
    /// <summary>
    /// ReadMod.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.5")]
    public enum ReadMod
    {
        
        /// <summary>
        /// ReadAndWrite.
        /// </summary>
        ReadAndWrite,
        
        /// <summary>
        /// ReadOnly.
        /// </summary>
        ReadOnly,
    }
}
